# Generated by Django 5.2.5 on 2025-08-19 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_couple_couplerequest_couple_unique_couple'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.couple')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.movie')),
            ],
        ),
    ]
